config/routes.rb
Rails.application.routes.draw do

  root 'dogs#index'
  
  resources :dogs

end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def edit
    @dog = Dog.find(params[:id])
    @dog_name = @dog.breed
  end

  def update
    dog = Dog.find(params[:id])
    dog.update(dog_params)
    redirect_to(dogs_path)
  end

  def new
    @dog = Dog.new
  end

  def create
    Dog.create(dog_params)
    redirect_to(dogs_path)
  end

  def destroy
    dog = Dog.find(params[:id])
    dog.destroy
    redirect_to(dogs_path)
  end

  private

  def dog_params
    params.require(:dog).permit(:breed, :color, :country_of_origin, :friendly, :history, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/edit.html.erb
<%= form_for @dog do |f| %>
  <%= f.label :breed %>
  <%= f.text_field :breed %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.label :color %>
  <%= f.text_field :color %>

  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>

  <%= f.label :friendly %>
  <%= f.text_field :friendly %>

  <%= f.label :history %>
  <%= f.text_field :history %>

  <%= f.submit 'Update breed' %>
<% end %>

app/views/dogs/index.html.erb
<div class="dog-list">
  <% @dogs.each do |dog| %>
      <div class="dog-index">
        <%= link_to dog_path(dog.id) do %>
          <%= image_tag(dog.image, class: 'index-image') %>
        <% end %>
        <p><%= dog.breed %></p>
        <%= link_to('Edit', edit_dog_path(dog.id), class: 'index-link') %>
        <%= link_to('Delete', dog_path(dog.id), method: :delete, class: 'index-link') %>
      </div>
  <% end %>
</div>

app/views/dogs/new.html.erb
<%= form_for @dog do |f| %>
  <%= f.label :breed %>
  <%= f.text_field :breed %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.label :color %>
  <%= f.text_field :color %>

  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>

  <%= f.label :friendly %>
  <%= f.text_field :friendly %>

  <%= f.label :history %>
  <%= f.text_field :history %>

  <%= f.submit 'Add a breed' %>
<% end %>

app/views/dogs/show.html.erb
<h1><%= @dog.breed %></h1>

<%= image_tag(@dog.image, class: 'show-image') %>

<h5>Colour: <%= @dog.color %></h5>

<h5>Country of origin: <%= @dog.country_of_origin %></h5>

<h5>Friendly: <%= @dog.friendly == true ? 'yes' : 'no' %></h5>

<p class="show-history"><%= @dog.history %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrudRailsHomework</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <nav>
      <li><%= link_to('HOME', dogs_path) %></li>
      <li><%= link_to('ADD NEW BREED', new_dog_path) %></li>
    </nav>
  </header>

<div class="<%= params[:action] %>-wrapper">
  <%= yield %>
</div>

</body>
</html>